before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
language: node_js
node_js:
  - "node"
  - "lts/*"
before_script:
  - npm run compile
  - npm run dist
env:
  - TEST_SUBJECT=src
  - TEST_SUBJECT=lib
  - TEST_SUBJECT=dist
